### ISSUE TITLE
Riot Valorant doesn't get cached

### ISSUE THREAD

**Issue by grabupdev** [uklans/cache-domains#230] opened 2023-09-16 11:19 UTC
### Describe the issue you are having
When downloading Valorant through Riot Games Launcher, it doesn't get cached. Steam Games, for example Rocket League are working.

### Describe your setup?

DNS Server: pfSense Firewall with 1.1.1.1 as upstream DNS
I am using lancache-dns with the pfSense Firewall DNS IP as Upstream DNS.
The IP of the lancache-dns is set as primary DNS on the Windows 11 Client. No secondary DNS Server is set.

### Are you running sniproxy
no

### DNS Configuration
```
USE_GENERIC_CACHE=true
LANCACHE_IP=10.10.10.50
DNS_BIND_IP=10.10.10.41
UPSTREAM_DNS=10.10.10.1
CACHE_ROOT=/opt/dlcache
CACHE_DISK_SIZE=500g
CACHE_INDEX_SIZE=500m
CACHE_MAX_AGE=3650d
TZ=Europe/Berlin
```

### Other stuff

When checking `iftop` on the NIC that is used for caching, i can see while downloading Valorant, that the Traffic is going through the cache. But it doesn't get cached.

I have seen that there already was an issue for this #164 but that didn't help.

**Comment by ciarancrocker** [comment] 2023-11-24 08:50
Updating this to add that this is still an issue. We see Valorant patching exclusively over HTTPS at the following hostnames:
* valorant.secure.dyn.riotcdn.net
* bacon.secure.dyn.riotcdn.net

These hostnames are poisoned to point to our cache according to the following file: https://github.com/uklans/cache-domains/blob/31b2ba1e0a7c419327cb97f589b508d78b9aecbf/riot.txt#L5

**Comment by Tawmu** [comment] 2023-11-24 08:56
Maybe @v3n can help?

**Comment by VibroAxe** [comment] 2024-01-02 23:19
@v3n anything you can assist with?

**Comment by v3n** [comment] 2024-01-23 15:27
Hey folks, I'm no longer at Riot, but have reached out to my old colleagues.

**Comment by xelaadryth** [comment] 2024-02-29 04:06
Oops, sorry this slipped off our radar for so long, getting some folks to look at this in the next few weeks.

**Comment by xelaadryth** [comment] 2024-03-15 20:36
So for some context, the fetching of the release manifest does require SSL for `https://valorant.secure.dyn.riotcdn.net`, and that's unavoidable. However, after that initial step, patching should fall back to `http://valorant.dyn.riotcdn.net` as long as that IP resolves to a non-public IP range such as your `10.`. I'm not that familiar with this repo, but would it be possible to set it up such that requests at `*.secure.dyn.riotcdn.net` skip the lan cache?

If that doesn't resolves the issue I can also dig further from our side

**Comment by MathewBurnett** [comment] 2024-03-15 21:36
The cache domains entry for lancache dns has had *.dyn.riotcdn.net redirect in it since jul 31st 2019. During that time valorant hasn't been falling back, lol has been working. I haven't looked at it recently but this issue was raised again here in sep 23. I expect its still not working as intended.

**Comment by xelaadryth** [comment] 2024-03-15 21:56
Yep looks like we have a suspect, testing out some fixes locally, will let ya folks know when we have a timeline for when the fix will hit live!

**Comment by jblazquez** [comment] 2024-03-15 23:08
Hi everyone,

I'm on the Riot patcher team and worked on the initial HTTP fallback feature for LAN parties [some 5 years ago](https://github.com/ti-mo/ansible-lanparty/issues/8#issuecomment-459892219).

Thank you for letting us know about this issue, and sorry for taking so long to address it. We have fixed the problem and you should see caching working again with the next version of Riot Client in early April.

If you encounter issues with caching again, please feel free to ping @xelaadryth or myself and we'll do our best to look into it.

**Comment by MathewBurnett** [comment] 2024-03-15 23:51
Much appreciated. Its always well received when we are able to tell our LAN goers the developers of their favorite games are trying to help us out.

**Comment by jblazquez** [comment] 2024-04-02 19:20
Hi all,

I just wanted to update this thread and let you know that Riot Client v83 is now live and contains the fix for this issue. You should be able to cache Valorant downloads now.

Please let us know if you are still encountering issues.

Thanks!

**Closed** 2024-05-10 06:36 UTC
