### ISSUE TITLE
Guild Wars 2 login error (Arenanet, Europe)

### ISSUE THREAD

**Issue by gr0ebi** [uklans/cache-domains#104] opened 2019-07-20 12:31 UTC
### Describe the issue you are having
arenanet cache domains are caching but login to Guild Wars 2 isn't possible - Error 58

### Describe your setup?
lancachenet/monolithic (docker) with Unbound Server with uklans/cache-domains git

lancachenet/monolithic: 10.0.0.200:80
lancachenet/sniproxy: 10.0.0.200:443

### Are you running sniproxy
Yes, also docker

### DNS Configuration
```
server:
  local-zone: "assetcdn.101.arenanetworks.com" redirect
  local-data: "assetcdn.101.arenanetworks.com 30 IN A 10.0.0.200"
  local-zone: "assetcdn.102.arenanetworks.com" redirect
  local-data: "assetcdn.102.arenanetworks.com 30 IN A 10.0.0.200"
  local-zone: "assetcdn.103.arenanetworks.com" redirect
  local-data: "assetcdn.103.arenanetworks.com 30 IN A 10.0.0.200"
  local-zone: "live.patcher.bladeandsoul.com" redirect
  local-data: "live.patcher.bladeandsoul.com 30 IN A 10.0.0.200"

```

### Sniproxy output
No output from sniproxy that is arenanet related

**Comment by VibroAxe** [comment] 2019-07-20 13:29
Any errors in your monolithic logs? Either access.log or error.log

**Comment by gr0ebi** [comment] 2019-07-20 13:47
only "errors" I see are non-related I would say

`
2019/07/20 14:39:40 [error] 1321#1321: *44802 upstream timed out (110: Connection timed out) while connecting to upstream, client: 10.0.0.175, server: , request: "GET /program/101/1/0/2115870/compressed HTTP/1.1", upstream: "http://99.86.245.205:80/program/101/1/0/2115870/compressed", host: "assetcdn.101.ArenaNetworks.com"
2019/07/20 14:40:10 [error] 1322#1322: *44800 upstream timed out (110: Connection timed out) while connecting to upstream, client: 10.0.0.175, server: , request: "GET /program/101/1/0/2093371/compressed HTTP/1.1", upstream: "http://99.86.245.146:80/program/101/1/0/2093371/compressed", host: "assetcdn.101.ArenaNetworks.com"
2019/07/20 14:40:41 [error] 1321#1321: *44802 upstream timed out (110: Connection timed out) while connecting to upstream, client: 10.0.0.175, server: , request: "GET /program/101/1/0/2115870/compressed HTTP/1.1", upstream: "http://99.86.245.146:80/program/101/1/0/2115870/compressed", host: "assetcdn.101.ArenaNetworks.com"
2019/07/20 14:40:43 [error] 1321#1321: *45310 upstream timed out (110: Connection timed out) while connecting to upstream, client: 10.0.0.175, server: , request: "GET /program/101/1/0/2093398/compressed HTTP/1.1", upstream: "http://99.86.245.205:80/program/101/1/0/2093398/compressed", host: "assetcdn.101.ArenaNetworks.com"
2019/07/20 14:40:43 [error] 1321#1321: *45305 upstream timed out (110: Connection timed out) while connecting to upstream, client: 10.0.0.175, server: , request: "GET /program/101/1/0/2101932/compressed HTTP/1.1", upstream: "http://99.86.245.131:80/program/101/1/0/2101932/compressed", host: "assetcdn.101.ArenaNetworks.com"
2019/07/20 14:41:26 [error] 1322#1322: *45304 upstream timed out (110: Connection timed out) while connecting to upstream, client: 10.0.0.175, server: , request: "GET /program/101/1/0/2087856/compressed HTTP/1.1", upstream: "http://99.86.245.131:80/program/101/1/0/2087856/compressed", host: "assetcdn.101.ArenaNetworks.com"
`

**Comment by VibroAxe** [comment] 2019-07-20 14:24
Looks like assetcdn.101 is having issues from your network. 

Step 1 sounds obvious but are you sure that this is currently working if you take monolithic offline and go direct?

**Comment by gr0ebi** [comment] 2019-07-20 14:29
> Step 1 sounds obvious but are you sure that this is currently working if you take monolithic offline and go direct?

If I bypass monolithic (using 8.8.8.8 as DNS on client) everything is working fine

**Comment by gr0ebi** [comment] 2019-07-20 15:26
I did some ping tests

pinging assetcdn.101.ArenaNetworks.com
`Min = 12ms, Max = 253ms, Mid = 31ms, Loss = 2%`

pinging 8.8.8.8
`Min = 18ms, Max = 239ms, Mid = 42ms, Loss = 2%`

pinging 139.130.4.5(Australian DNS, far far away from mid europe)
`Min = 367ms, Max = 476ms, Mid = 390ms, Loss = 0%`

pinging 185.139.32.19 (near server in europe)
`Min = 23ms, Max = 149ms, Mid = 45ms, Loss = 0%`

**Comment by manafoo** [comment] 2019-07-21 21:02
I can confirm on monolithic gw2 updates and installation doesn't work

**Comment by manafoo** [comment] 2019-07-21 21:22
Can you pls remove gw2 because i have to reset dns for people everytime  someone wants to play gw2

**Comment by gr0ebi** [comment] 2019-07-23 13:38
Is there anything I can do to provide more info?

**Comment by Lepidopterist** [comment] 2019-07-31 08:56
Hey all,

We're aware of this - hopefully we will be able to test this over this coming weekend and confirm.

**Comment by gr0ebi** [comment] 2019-07-31 17:08
> We're aware of this - hopefully we will be able to test this over this coming weekend and confirm.
> 
>

Thx for your effort

**Comment by MathewBurnett** [comment] 2019-07-31 17:17
I have been unable to confirm your issue. I have a cache, SNI, and DNS setup
- Downloaded installer from scratch
- Started install (both patcher and game downloaded as expected, from assetcdn.101.arenanetworks.com)
- logged in to installer without issue
- game starts and plays without issue

**Comment by gr0ebi** [comment] 2019-07-31 17:48
>I have been unable to confirm your issue. I >have a cache, SNI, and DNS setup

Are you also located in Europe?
Might only be caused by CDN in Europe...
Is your SNI showing anything arenanet related?

**Comment by MathewBurnett** [comment] 2019-07-31 17:49
in the UK, nothing at all in the SNI logs

**Comment by gr0ebi** [comment] 2019-07-31 17:54
OK, I will be at home in about 1-2hours, I gonna check with wireshark on client and analyze all logs in my containers

Thanks!

**Comment by manafoo** [comment] 2019-08-05 01:04
> in the UK, nothing at all in the SNI logs

can you wait untill u get an update and try to update it through the containers ?

**Comment by manafoo** [comment] 2019-08-05 23:52
i don't know if you guys fixed it or the fact that i switched back to ubuntu 18.4 from kubuntu 19 fixed it , either way i think it works fine now , i need to give it more time and update the game few more times to make sure

**Comment by gr0ebi** [comment] 2019-08-06 19:45
It realy seems to work now! I tested it on 3 different clients, there wasn't a update though

**Comment by unspec** [comment] 2019-08-07 09:29
Ok, well if its all working now we'll close this issue. Should it reoccur let us know and we can try to see whats going on.

**Closed by unspec** 2019-08-07 09:29 UTC

**Comment by gr0ebi** [comment] 2019-08-07 12:46
There was an update this night, it wasn't downloaded at all with cache active
The login into gw2 is working though, which was broken for weeks
